import { useEffect, useMemo, useState } from "react";
import { apiOrigin } from "../../config/runtime.js";
import "./install.css";

const frameworkVariables = [
  ["DATABASE_URL", "数据库连接", true, "postgres://user:password@host:5432/database"], ["REDIS_URL", "Redis 连接", true, "redis://host:6379/0"],
  ["PUBLIC_WEB_ORIGIN", "前台域名", false, "https://example.com"], ["API_ORIGIN", "API 域名", false, "https://example.com"], ["PRIMARY_DOMAIN", "主域名", false, "example.com"], ["TEST_DOMAIN_SUFFIX", "测试域名后缀", false, "-test"],
  ["IDENTITY_ISSUER", "身份平台 Issuer", false, "https://passport.example.com"], ["IDENTITY_AUTHORIZATION_ENDPOINT", "身份授权地址", false, "https://passport.example.com/oauth2/authorize"], ["IDENTITY_TOKEN_ENDPOINT", "身份 Token 地址", false, "https://passport.example.com/oauth2/token"], ["IDENTITY_USERINFO_ENDPOINT", "身份 UserInfo 地址", false, "https://passport.example.com/userinfo"], ["IDENTITY_JWKS_URL", "身份 JWKS 地址", false, "https://passport.example.com/oauth2/jwks"], ["IDENTITY_AUDIENCE", "身份 Audience", false, "auth-template-api"], ["IDENTITY_CLIENT_ID", "身份 Client ID", false, "client-id"], ["IDENTITY_CLIENT_SECRET", "身份 Client Secret", true, "输入 Client Secret"], ["IDENTITY_REDIRECT_URI", "OIDC 回调地址", false, "https://example.com/v1/auth/callback"], ["IDENTITY_APPLICATION_CODE", "身份 Application Code", false, "app-auth-template"], ["IDENTITY_SCOPES", "身份 Scope", false, "openid,profile,email"],
  ["MANIFEST_SYNC_INTERVAL", "Manifest 同步周期", false, "10m"], ["SESSION_COOKIE_NAME", "Session Cookie 名称", false, "auth_template_session"], ["SESSION_TTL", "Session 有效期", false, "8h"], ["SESSION_SECURE", "仅通过 HTTPS 发送 Cookie", false, "true"], ["SESSION_SAME_SITE", "Cookie SameSite", false, "Lax"], ["SESSION_ENCRYPTION_KEY", "Session 加密密钥", true, "RawStdEncoding 32 字节密钥"], ["ALLOWED_ORIGINS", "允许的浏览器 Origin", false, "https://example.com"], ["METRICS_TOKEN", "Metrics Token", true, "输入 Metrics Token"], ["LOG_MODE", "日志模式", false, "local_file"], ["LOG_LEVEL", "日志级别", false, "info"], ["LOG_OUTPUT", "日志路径", false, "/var/log/auth-template"], ["LOG_RETENTION_DAYS", "日志保留天数", false, "180"], ["DEBUG", "调试开关", false, "false"],
];
const emptyValues = () => Object.fromEntries(frameworkVariables.map(([key]) => [key, ""]));

async function jsonRequest(path, options = {}) { const response = await fetch(`${apiOrigin()}${path}`, { credentials: "same-origin", ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.error?.message || "安装请求失败"); return body; }

export function InstallPage() {
  const [status, setStatus] = useState(null); const [values, setValues] = useState(emptyValues); const [custom, setCustom] = useState([{ key: "", value: "", description: "", isSecret: true }]); const [installKey, setInstallKey] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(null);
  useEffect(() => { jsonRequest("/v1/install/status").then((value) => { setStatus(value.data); if (value.data?.installed) window.location.assign("/"); }).catch(setError); }, []);
  const entries = useMemo(() => [...frameworkVariables.map(([key, description, isSecret]) => ({ key, description, isSecret, value: values[key] })).filter((item) => item.value), ...custom.filter((item) => item.key || item.value)], [values, custom]);
  const submit = async (event) => { event.preventDefault(); if (!installKey || !entries.length) return; setBusy(true); setError(null); try { await jsonRequest("/v1/install/configuration", { method: "PUT", headers: { "X-Install-Key": installKey }, body: JSON.stringify({ entries }) }); window.location.assign("/"); } catch (value) { setError(value); } finally { setBusy(false); } };
  if (!status) return <main className="install-shell"><section className="install-card"><p>正在检查安装状态…</p>{error && <p className="install-error">{error.message}</p>}</section></main>;
  if (!status.available) return <main className="install-shell"><section className="install-card"><span className="install-kicker">SECHELPER COMMUNITY</span><h1>安装引导不可用</h1><p>当前服务未开启首次安装模式，请联系部署管理员。</p></section></main>;
  return <main className="install-shell"><section className="install-card"><span className="install-kicker">FIRST RUN INSTALLATION</span><h1>首次运行安装引导</h1><p className="install-lead">填写框架环境变量和业务自定义变量。敏感值会加密保存，安装完成后此页面自动关闭。</p><form onSubmit={submit}><label className="install-key-field"><span>安装密钥</span><input type="password" value={installKey} onChange={(event) => setInstallKey(event.target.value)} placeholder="输入部署提供的安装密钥" required /></label><h2>框架环境变量</h2><div className="install-grid">{frameworkVariables.map(([key, label, secret, placeholder]) => <label key={key}><span>{label}<code>{key}</code></span><input type={secret ? "password" : "text"} value={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.value })} placeholder={placeholder} autoComplete="new-password" /></label>)}</div><div className="install-custom-heading"><h2>业务自定义变量</h2><button type="button" onClick={() => setCustom([...custom, { key: "", value: "", description: "", isSecret: true }])}>添加变量</button></div>{custom.map((item, index) => <div className="install-custom-row" key={index}><input value={item.key} onChange={(event) => setCustom(custom.map((current, row) => row === index ? { ...current, key: event.target.value.toUpperCase() } : current))} placeholder="BUSINESS_FEATURE_KEY" pattern="[A-Z][A-Z0-9_]{0,127}" /><input value={item.description} onChange={(event) => setCustom(custom.map((current, row) => row === index ? { ...current, description: event.target.value } : current))} placeholder="说明" /><input type={item.isSecret ? "password" : "text"} value={item.value} onChange={(event) => setCustom(custom.map((current, row) => row === index ? { ...current, value: event.target.value } : current))} placeholder="变量值" autoComplete="new-password" /><label><input type="checkbox" checked={item.isSecret} onChange={(event) => setCustom(custom.map((current, row) => row === index ? { ...current, isSecret: event.target.checked } : current))} />敏感</label></div>)}{error && <p className="install-error">{error.message}</p>}<button className="install-submit" disabled={busy}>{busy ? "安装中…" : "保存并完成安装"}</button></form></section></main>;
}
