FROM node:22-alpine AS build
WORKDIR /src/web
COPY web/package*.json ./
RUN npm ci
COPY web .
RUN npm run build

WORKDIR /src/web/admin
COPY web/admin/package*.json ./
RUN npm ci
COPY web/admin .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /src/web/dist /usr/share/nginx/html
COPY --from=build /src/web/admin/dist /usr/share/nginx/html/admin
