import { useEffect, useState } from "react";
import { configurationApi } from "./api.js";
import { ErrorState, Loading, PageHeader } from "../../app/components.jsx";
import { EmptyState, RefreshButton } from "../../shared/ui.jsx";

export function ConfigurationPage() {
  const [rows, setRows] = useState(null); const [error, setError] = useState(null); const [busy, setBusy] = useState(false); const [key, setKey] = useState(""); const [form, setForm] = useState({ value: "", description: "", isSecret: true });
  const load = async () => { setError(null); try { const result = await configurationApi.list(); setRows(result.data || []); } catch (value) { setError(value); } };
  useEffect(() => { load(); }, []);
  const edit = async (entry) => { setKey(entry.key); setForm({ value: "", description: entry.description || "", isSecret: entry.isSecret }); if (!entry.isSecret) { const result = await configurationApi.get(entry.key); setForm({ value: result.data?.value || "", description: entry.description || "", isSecret: false }); } };
  const save = async (event) => { event.preventDefault(); if (!key.trim() || !form.value) return; setBusy(true); try { await configurationApi.save(key.trim().toUpperCase(), form); setKey(""); setForm({ value: "", description: "", isSecret: true }); await load(); } catch (value) { setError(value); } finally { setBusy(false); } };
  const remove = async (entry) => { if (!window.confirm(`确认删除 ${entry.key}？`)) return; setBusy(true); try { await configurationApi.remove(entry.key); if (key === entry.key) setKey(""); await load(); } catch (value) { setError(value); } finally { setBusy(false); } };
  if (error && !rows) return <><PageHeader code="PLATFORM" title="配置中心" description="集中管理应用和业务模块可读取的环境变量。" /><ErrorState error={error} retry={load} /></>;
  if (!rows) return <Loading text="正在加载配置中心…" />;
  return <><PageHeader code="PLATFORM" title="配置中心" description="值在数据库中加密保存，业务模块通过宿主提供的只读配置接口读取；修改将在下次启动时对启动配置生效。" /><div className="card" style={{ marginBottom: 16 }}><form onSubmit={save} style={{ display: "grid", gap: 12 }}><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}><label>环境变量名<input value={key} onChange={(event) => setKey(event.target.value.toUpperCase())} placeholder="REDIS_URL" pattern="[A-Z][A-Z0-9_]{0,127}" required /></label><label>说明<input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="例如：业务缓存连接" /></label></div><label>值<input type={form.isSecret ? "password" : "text"} value={form.value} onChange={(event) => setForm({ ...form, value: event.target.value })} placeholder={form.isSecret && key ? "输入新值以替换已保存的密文" : "配置值"} required /></label><label><input type="checkbox" checked={form.isSecret} onChange={(event) => setForm({ ...form, isSecret: event.target.checked })} /> 敏感值（后台列表不显示明文）</label><div><button type="submit" disabled={busy}>{busy ? "保存中…" : key ? "保存配置" : "新增配置"}</button>{key && <button type="button" onClick={() => setKey("")} style={{ marginLeft: 8 }}>取消</button>}</div></form></div><section className="card">{rows.length ? <table><thead><tr><th>变量名</th><th>说明</th><th>类型</th><th>版本</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{rows.map((entry) => <tr key={entry.key}><td><code>{entry.key}</code></td><td>{entry.description || "—"}</td><td>{entry.isSecret ? "敏感值" : "普通值"}</td><td>{entry.version}</td><td>{new Date(entry.updatedAt).toLocaleString()}</td><td><button type="button" onClick={() => edit(entry)}>编辑</button><button type="button" onClick={() => remove(entry)} style={{ marginLeft: 8 }}>删除</button></td></tr>)}</tbody></table> : <EmptyState title="暂无配置" description="新增一个环境变量后，业务模块可以通过配置提供者读取它。" />}<div style={{ marginTop: 12 }}><RefreshButton onClick={load} busy={busy} /></div></section></>;
}
